### ISSUE TITLE
Trees and wind effect on personal site

### ISSUE THREAD

**Issue by mysticaltech** [a-type/clouds#1]
Hey @a-type, I know a wizard when I see one 🙂 , so glad to have found you. The trees and wind effect on your personal site are simply next-level, are you using react-three-fiber like you do for this project?

**Comment by a-type** [comment]
Lol, thanks! Nope, I actually simplified my website dramatically to improve mobile performance. I just use a video I took outside my apartment, with a couple of CSS filters applied.

**Comment by mysticaltech** [comment]
Ah niiice, didn't know that we could overlay css effects over video, cool! Sometimes the simplest solutions are the most elegant ones!
